//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermissionsInheritancePOC.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CompanyDepartmentEmployeeEntities : DbContext
    {
        public CompanyDepartmentEmployeeEntities()
            : base("name=CompanyDepartmentEmployeeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Identity_table> Identity_table { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Security_object> Security_object { get; set; }
        public virtual DbSet<Unit_type> Unit_type { get; set; }
    
        [DbFunction("CompanyDepartmentEmployeeEntities", "getIdentitySecuribleObjects")]
        public virtual IQueryable<getIdentitySecuribleObjects_Result> getIdentitySecuribleObjects(Nullable<int> identityId)
        {
            var identityIdParameter = identityId.HasValue ?
                new ObjectParameter("identityId", identityId) :
                new ObjectParameter("identityId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<getIdentitySecuribleObjects_Result>("[CompanyDepartmentEmployeeEntities].[getIdentitySecuribleObjects](@identityId)", identityIdParameter);
        }
    
        [DbFunction("CompanyDepartmentEmployeeEntities", "GetRec")]
        public virtual IQueryable<GetRec_Result> GetRec(Nullable<int> ss)
        {
            var ssParameter = ss.HasValue ?
                new ObjectParameter("ss", ss) :
                new ObjectParameter("ss", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetRec_Result>("[CompanyDepartmentEmployeeEntities].[GetRec](@ss)", ssParameter);
        }
    
        [DbFunction("CompanyDepartmentEmployeeEntities", "GetRec2")]
        public virtual IQueryable<GetRec2_Result> GetRec2(Nullable<int> ss)
        {
            var ssParameter = ss.HasValue ?
                new ObjectParameter("ss", ss) :
                new ObjectParameter("ss", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetRec2_Result>("[CompanyDepartmentEmployeeEntities].[GetRec2](@ss)", ssParameter);
        }
    
        [DbFunction("CompanyDepartmentEmployeeEntities", "getSecuribleObjectPermissions")]
        public virtual IQueryable<getSecuribleObjectPermissions_Result> getSecuribleObjectPermissions(Nullable<int> securibleObjectId)
        {
            var securibleObjectIdParameter = securibleObjectId.HasValue ?
                new ObjectParameter("securibleObjectId", securibleObjectId) :
                new ObjectParameter("securibleObjectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<getSecuribleObjectPermissions_Result>("[CompanyDepartmentEmployeeEntities].[getSecuribleObjectPermissions](@securibleObjectId)", securibleObjectIdParameter);
        }
    
        [DbFunction("CompanyDepartmentEmployeeEntities", "getSecuribleObjectPermissionsTest")]
        public virtual IQueryable<getSecuribleObjectPermissionsTest_Result> getSecuribleObjectPermissionsTest(Nullable<int> securibleObjectId)
        {
            var securibleObjectIdParameter = securibleObjectId.HasValue ?
                new ObjectParameter("securibleObjectId", securibleObjectId) :
                new ObjectParameter("securibleObjectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<getSecuribleObjectPermissionsTest_Result>("[CompanyDepartmentEmployeeEntities].[getSecuribleObjectPermissionsTest](@securibleObjectId)", securibleObjectIdParameter);
        }
    
        public virtual int addCompany_(Nullable<int> id, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addCompany_", idParameter, nameParameter);
        }
    
        public virtual int addDepartment(Nullable<int> id, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addDepartment", idParameter, nameParameter);
        }
    
        public virtual int addEmployee(Nullable<int> id, string name)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addEmployee", idParameter, nameParameter);
        }
    
        public virtual int addIdentity_table(Nullable<int> id, Nullable<int> parrent_id, Nullable<int> company_id, Nullable<int> department_id, Nullable<int> employee_id, Nullable<int> type_id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var parrent_idParameter = parrent_id.HasValue ?
                new ObjectParameter("parrent_id", parrent_id) :
                new ObjectParameter("parrent_id", typeof(int));
    
            var company_idParameter = company_id.HasValue ?
                new ObjectParameter("company_id", company_id) :
                new ObjectParameter("company_id", typeof(int));
    
            var department_idParameter = department_id.HasValue ?
                new ObjectParameter("department_id", department_id) :
                new ObjectParameter("department_id", typeof(int));
    
            var employee_idParameter = employee_id.HasValue ?
                new ObjectParameter("employee_id", employee_id) :
                new ObjectParameter("employee_id", typeof(int));
    
            var type_idParameter = type_id.HasValue ?
                new ObjectParameter("type_id", type_id) :
                new ObjectParameter("type_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addIdentity_table", idParameter, parrent_idParameter, company_idParameter, department_idParameter, employee_idParameter, type_idParameter);
        }
    
        public virtual ObjectResult<CreateUnitTable_Result> CreateUnitTable()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CreateUnitTable_Result>("CreateUnitTable");
        }
    
        public virtual ObjectResult<getNamesWithPermissions_Result> getNamesWithPermissions(Nullable<int> securibleObjectId)
        {
            var securibleObjectIdParameter = securibleObjectId.HasValue ?
                new ObjectParameter("securibleObjectId", securibleObjectId) :
                new ObjectParameter("securibleObjectId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getNamesWithPermissions_Result>("getNamesWithPermissions", securibleObjectIdParameter);
        }
    
        public virtual ObjectResult<getSecurityObjectByName_Result> getSecurityObjectByName(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSecurityObjectByName_Result>("getSecurityObjectByName", nameParameter);
        }
    
        public virtual ObjectResult<getSecurityObjectsList_Result> getSecurityObjectsList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSecurityObjectsList_Result>("getSecurityObjectsList");
        }
    }
}
