//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermissionsInheritancePOC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Identity_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Identity_table()
        {
            this.Identity_table1 = new HashSet<Identity_table>();
            this.Permissions = new HashSet<Permission>();
        }
    
        public int id { get; set; }
        public Nullable<int> parrent_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> type_id { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Identity_table> Identity_table1 { get; set; }
        public virtual Identity_table Identity_table2 { get; set; }
        public virtual Unit_type Unit_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permission> Permissions { get; set; }
    }
}
