//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PermissionsInheritancePOC.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int id { get; set; }
        public int security_object_id { get; set; }
        public int identity_id { get; set; }
    
        public virtual Identity_table Identity_table { get; set; }
        public virtual Security_object Security_object { get; set; }
    }
}
